# Pytorch Fundamentals

In [1]:
!nvidia-smi

Tue May 21 17:30:29 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P8              14W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd  # type: ignore
import torch

from IPython.display import display

print(torch.__version__)

2.3.0+cu121


## Introduction to Tensor

### Creating Tensors

In [7]:
# Scalar
scalar: torch.Tensor = torch.tensor(9)
print(scalar, scalar.ndim, scalar.item(), sep="\n")

tensor(9)
0
9


In [11]:
# Vector
vector: torch.Tensor = torch.Tensor([9, -9])
print(vector, vector.ndim, vector.shape, sep="\n")

tensor([ 9., -9.])
1
torch.Size([2])


In [18]:
# MATRIX
matrix: torch.Tensor = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(matrix, matrix.ndim, matrix.shape, matrix[0], sep="\n")

tensor([[1., 2., 3.],
        [4., 5., 6.]])
2
torch.Size([2, 3])
tensor([1., 2., 3.])


In [27]:
# TENSOR
tensor: torch.Tensor = torch.tensor(
    [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], dtype=torch.complex64
)
print(
    tensor,
    tensor.ndim,
    tensor.shape,
    tensor[0],
    tensor[0][0],
    tensor[0][0][0],
    sep="\n",
)

tensor([[[1.+0.j, 2.+0.j, 3.+0.j],
         [4.+0.j, 5.+0.j, 6.+0.j],
         [7.+0.j, 8.+0.j, 9.+0.j]]])
3
torch.Size([1, 3, 3])
tensor([[1.+0.j, 2.+0.j, 3.+0.j],
        [4.+0.j, 5.+0.j, 6.+0.j],
        [7.+0.j, 8.+0.j, 9.+0.j]])
tensor([1.+0.j, 2.+0.j, 3.+0.j])
tensor(1.+0.j)
