# Pytorch Fundamentals

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch

from IPython.display import display

print(torch.__version__)

2.3.0+cu121


## Introduction to Tensor

### Creating Tensors

In [3]:
# Scalar
scalar: torch.Tensor = torch.tensor(9)
print(scalar, scalar.ndim, scalar.item(), sep = "\n")

tensor(9)
0
9


In [4]:
# Vector
vector: torch.Tensor = torch.Tensor([9, -9])
print(vector, vector.ndim, vector.shape, sep = "\n")

tensor([ 9., -9.])
1
torch.Size([2])


In [23]:
# MATRIX
MATRIX: torch.Tensor = torch.Tensor([[0, 1, 2, 3],
                                     [3, 4, 5, 6],
                                     [6, 7, 8, 9]])
print(MATRIX, MATRIX.ndim, MATRIX.shape, MATRIX[0], sep = "\n")

tensor([[0., 1., 2., 3.],
        [3., 4., 5., 6.],
        [6., 7., 8., 9.]])
2
torch.Size([3, 4])
tensor([0., 1., 2., 3.])


In [6]:
# TENSOR
TENSOR: torch.Tensor = torch.tensor([[[1, 2, 3],
                                      [4, 5, 6],
                                      [7, 8, 9]]], dtype = torch.complex64)
print(TENSOR, TENSOR.ndim, TENSOR.shape, TENSOR[0], TENSOR[0][0], TENSOR[0][0][0], sep = "\n")

tensor([[[1.+0.j, 2.+0.j, 3.+0.j],
         [4.+0.j, 5.+0.j, 6.+0.j],
         [7.+0.j, 8.+0.j, 9.+0.j]]])
3
torch.Size([1, 3, 3])
tensor([[1.+0.j, 2.+0.j, 3.+0.j],
        [4.+0.j, 5.+0.j, 6.+0.j],
        [7.+0.j, 8.+0.j, 9.+0.j]])
tensor([1.+0.j, 2.+0.j, 3.+0.j])
tensor(1.+0.j)


### Random Tensors

In [18]:
rand_tensor: torch.Tensor = torch.rand(size = (224, 224, 3)) # height, width, number of color channels
print(rand_tensor.ndim, rand_tensor.shape, sep = "\n")

3
torch.Size([224, 224, 3])


### Tensors with all zeros and all ones

In [26]:
zeros_tensor: torch.Tensor = torch.zeros(3, 4)
print(zeros_tensor, zeros_tensor.ndim, zeros_tensor.shape, sep = "\n")

ones_tensor: torch.Tensor = torch.ones(3, 4)
print(ones_tensor, ones_tensor.ndim, ones_tensor.shape, sep = "\n")
print(ones_tensor.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
2
torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
2
torch.Size([3, 4])
torch.float32
